name: layoff_risk
version: '1.0.0'
config-version: 2

profile: layoff_risk

model-paths: ["models"]

target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  layoff_risk:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: table
